name: Second attempt across jobs.
on: [ push, pull_request ]

jobs:
  setup_variables:
    ## Setup variables for build info.
    name: Setup environment variables.
    runs-on: ubuntu-latest
    outputs:
      build_named: ${{ steps.set_vars.outputs.build_name }}

    steps:
      - name: Set Variables
        id: set_vars
        run: |
          echo ::set-output name=build_name::foo

  consume_variables:
    name: Consume environment variables.
    needs: setup_variables
    runs-on: ubuntu-latest
    # runs-on: ${{ matrix.operating-system }}
    # strategy:
    #   matrix:
    #     operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Output
      run: |
        echo " Job: ${{ toJson( needs.setup_variables ) }}"
        echo "Outs: ${{ toJson( needs.setup_variables.outputs ) }}"
        echo "Name: ${{ needs.setup_variables.outputs.build_named }}"
